//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Checkin
    {
        public int MaCheckin { get; set; }
        public string MaNV { get; set; }
        public string TrangThaici { get; set; }
        public Nullable<System.TimeSpan> Timeci { get; set; }
        public Nullable<System.DateTime> NgayThangci { get; set; }
        public string ThietBici { get; set; }
        public string HinhAnhci { get; set; }
        public string SaiLechci { get; set; }
        public string DiaDiemci { get; set; }
    }
}
