//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Xinnghiphep
    {
        public int MaNghiPhep { get; set; }
        public string MaNV { get; set; }
        public string LoaiNghi { get; set; }
        public System.DateTime NgayNghi { get; set; }
        public string TieuDeNghi { get; set; }
        public string LyDoNghi { get; set; }
        public string TrangThai { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
    }
}
