//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Xindimuonvesom
    {
        public int MaDMVS { get; set; }
        public string MaNV { get; set; }
        public string LoaiDMVS { get; set; }
        public System.DateTime NgayDMVS { get; set; }
        public System.TimeSpan GioXin { get; set; }
        public string TieuDeDMVS { get; set; }
        public string LyDoDMVS { get; set; }
        public string TrangThai { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
    }
}
