//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Checkout
    {
        public int MaCheckout { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.TimeSpan> Timeco { get; set; }
        public string TrangThaico { get; set; }
        public Nullable<System.DateTime> NgayThangco { get; set; }
        public string ThietBico { get; set; }
        public string HinhAnhco { get; set; }
        public string SaiLechco { get; set; }
        public string DiaDiemco { get; set; }
    }
}
