//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_ChamCong
    {
        public string MaChamCong { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
        public Nullable<int> MaCheckin { get; set; }
        public Nullable<int> MaCheckout { get; set; }
        public Nullable<int> MaCa { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayThang { get; set; }
    }
}
