//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_Cauhinhcongthuc
    {
        public string Macauhinh { get; set; }
        public System.DateTime Ngayapdung { get; set; }
        public bool IsCurrent { get; set; }
        public double BHXH { get; set; }
        public double BHYT { get; set; }
        public double BHTN { get; set; }
        public int BHXHMAX { get; set; }
        public double Phicongdoan { get; set; }
        public int PhicongdoanMax { get; set; }
        public int TinhThueTNCN { get; set; }
        public int Chinguoiphuthuoc { get; set; }
        public double Tangcathuong { get; set; }
        public double Tangchunhat { get; set; }
        public double Tangnghile { get; set; }
        public string Nguoiky { get; set; }
        public string Chucvunguoiky { get; set; }
        public System.DateTime Ngayky { get; set; }
        public string Mota { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
    }
}
