//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DsChamCong
    {
        public string TenNV { get; set; }
        public string Tenphong { get; set; }
        public string TrangThaici { get; set; }
        public string HinhAnhci { get; set; }
        public Nullable<System.DateTime> NgayThangci { get; set; }
        public Nullable<System.TimeSpan> Timeci { get; set; }
        public string ThietBici { get; set; }
        public string TrangThaico { get; set; }
        public string HinhAnhco { get; set; }
        public Nullable<System.DateTime> NgayThangco { get; set; }
        public Nullable<System.TimeSpan> Timeco { get; set; }
        public string ThietBico { get; set; }
        public string TrangThai { get; set; }
    }
}
