//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_Danhgianhanvien
    {
        public string Madanhgia { get; set; }
        public string MaNV { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Tinhthankyluat { get; set; }
        public string Ketqualamviec { get; set; }
        public string Daoduc { get; set; }
        public string Tinhthanhochoi { get; set; }
        public string Tinhthanlamviec { get; set; }
        public string Danhgiachung { get; set; }
        public double Diem { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
    }
}
