//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_KyluatNhanvien
    {
        public string Makyluat { get; set; }
        public string MaNV { get; set; }
        public string Tenkyluat { get; set; }
        public System.DateTime Ngayxayra { get; set; }
        public System.DateTime Ngaykyluat { get; set; }
        public string Diadiem { get; set; }
        public string Nguoichungkien { get; set; }
        public string Motasuviec { get; set; }
        public string Hinhthuckyluat { get; set; }
        public string Nguoibikyluatgiaithich { get; set; }
        public string LyDo { get; set; }
        public string Nguoiky { get; set; }
        public string Chucvunguoiky { get; set; }
        public System.DateTime Ngayky { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
    }
}
