//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_Luongtoithieu
    {
        public string MaLTT { get; set; }
        public System.DateTime Ngayapdung { get; set; }
        public bool IsCurrent { get; set; }
        public int Sotien { get; set; }
        public string Nguoiky { get; set; }
        public string Chucvunguoiky { get; set; }
        public System.DateTime Ngayky { get; set; }
        public string Mota { get; set; }
        public string GhiChu { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
    }
}
