//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_TuyenDung
    {
        public int Matuyendung { get; set; }
        public string HoNV { get; set; }
        public string TenNV { get; set; }
        public string Gioitinh { get; set; }
        public System.DateTime Ngaysinh { get; set; }
        public string Noisinh { get; set; }
        public string Diachi { get; set; }
        public string Dienthoaididong { get; set; }
        public string Email { get; set; }
        public string Ungtuyenvitri { get; set; }
        public string Chuyenmon { get; set; }
        public string Trangthai { get; set; }
        public string LinkCV { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
    }
}
