//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNSEntities : DbContext
    {
        public QLNSEntities()
            : base("name=QLNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIC_BacLuong> DIC_BacLuong { get; set; }
        public virtual DbSet<DIC_Bangcap> DIC_Bangcap { get; set; }
        public virtual DbSet<DIC_Calam> DIC_Calam { get; set; }
        public virtual DbSet<DIC_Cauhinhcongthuc> DIC_Cauhinhcongthuc { get; set; }
        public virtual DbSet<DIC_ChamCong> DIC_ChamCong { get; set; }
        public virtual DbSet<DIC_Checkin> DIC_Checkin { get; set; }
        public virtual DbSet<DIC_Checkout> DIC_Checkout { get; set; }
        public virtual DbSet<DIC_Chucvu> DIC_Chucvu { get; set; }
        public virtual DbSet<DIC_Chuyenmon> DIC_Chuyenmon { get; set; }
        public virtual DbSet<DIC_Congviec> DIC_Congviec { get; set; }
        public virtual DbSet<DIC_NgachLuong> DIC_NgachLuong { get; set; }
        public virtual DbSet<DIC_Xindimuonvesom> DIC_Xindimuonvesom { get; set; }
        public virtual DbSet<DIC_Xingapdoitac> DIC_Xingapdoitac { get; set; }
        public virtual DbSet<DIC_Xinnghiphep> DIC_Xinnghiphep { get; set; }
        public virtual DbSet<DIC_Xinquenchamcong> DIC_Xinquenchamcong { get; set; }
        public virtual DbSet<PB_Danhgianhanvien> PB_Danhgianhanvien { get; set; }
        public virtual DbSet<PB_Danhsachbangluong> PB_Danhsachbangluong { get; set; }
        public virtual DbSet<PB_Dicongtac> PB_Dicongtac { get; set; }
        public virtual DbSet<PB_KhautruNhanvien> PB_KhautruNhanvien { get; set; }
        public virtual DbSet<PB_KhenthuongNhanvien> PB_KhenthuongNhanvien { get; set; }
        public virtual DbSet<PB_KyluatNhanvien> PB_KyluatNhanvien { get; set; }
        public virtual DbSet<PB_Luonglamthem> PB_Luonglamthem { get; set; }
        public virtual DbSet<PB_Luongtangca> PB_Luongtangca { get; set; }
        public virtual DbSet<PB_Luongtoithieu> PB_Luongtoithieu { get; set; }
        public virtual DbSet<PB_Nhanvien> PB_Nhanvien { get; set; }
        public virtual DbSet<PB_Phongban> PB_Phongban { get; set; }
        public virtual DbSet<PB_SoLuong> PB_SoLuong { get; set; }
        public virtual DbSet<PB_TamungNhanvien> PB_TamungNhanvien { get; set; }
        public virtual DbSet<PB_ToNhom> PB_ToNhom { get; set; }
        public virtual DbSet<PB_TuyenDung> PB_TuyenDung { get; set; }
        public virtual DbSet<SYS_Nguoidung> SYS_Nguoidung { get; set; }
        public virtual DbSet<SYS_Quyen> SYS_Quyen { get; set; }
        public virtual DbSet<DsChamCong> DsChamCongs { get; set; }
        public virtual DbSet<LoginRole> LoginRoles { get; set; }
        public virtual DbSet<tinh_luong> tinh_luong { get; set; }
    }
}
