//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tinh_luong
    {
        public string MaNV { get; set; }
        public string HoNV { get; set; }
        public string TenNV { get; set; }
        public int Tongphucap { get; set; }
        public int luonglamthem { get; set; }
        public int khautru { get; set; }
        public int Tongthuong { get; set; }
        public int Phicongtac { get; set; }
        public int Tiendongthue { get; set; }
        public double Phicongdoan { get; set; }
        public double LCB { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> KPCĐ { get; set; }
        public Nullable<double> TienLuong { get; set; }
        public double LuongTangCa { get; set; }
        public Nullable<double> ThucLanh { get; set; }
    }
}
